#!/usr/bin/env bash
# This script configures a new Ubuntu machine to:
# Install nginx on my web-01 server
apt-get -y update
apt-get -y install nginx

# Make Nginx listen on port 80
# it is already the default case

# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
echo "Hello World!\n" > /var/www/html/index.nginx-debian.html

service nginx start
