#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Ammar-Khaled permanent;/" /etc/nginx/sites-available/default
service nginx start
