#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Ammar-Khaled permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx start
