#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Ammar-Khaled permanent;/" /etc/nginx/sites-available/default
sudo sed -i "/default_type application/a\ \n\t error_page 404 /404.html;" /etc/nginx/nginx.conf
sudo service nginx start
