#!/bin/bash
# This script generates a MySQL dump backup and creates a compressed archive out of it.

sudo mysqldump -u root -p "$1" --all-databases | sudo tee backup.sql
tar -czvf "$(date +'%d-%m-%Y').tar.gz" backup.sql
