#!/usr/bin/env bash
# This script generates a MySQL dump backup and creates a compressed archive out of it.

mysqldump --all-databases -u root -p"$1" | sudo tee backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
