#!/usr/bin/env bash
# This script makes nginx listen on port 80 of all the server’s active IPv4 IPs
sed -i "s/8080/80" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx restart
