#!/usr/bin/env bash
# displays a list of currently running processes.

ps -aux --forest

# ps: display processes information.
# -a: display information about all users and processes on the system, not just those associated with the current terminal.
# -u: display detailed user-oriented information about each process,
#+ including the user that owns the process, the CPU and memory usage, and the start time of the process.
# -x: display information about processes that are not associated with a terminal, such as background processes.
