#!/usr/bin/env bash
# bash script to handle pid with files and signals

echo $$ > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
while true
do
    echo ""
    sleep 2
done
