#!/usr/bin/env bash
# displays Best School 10 times using while loop and Hi in 9th iteration

counter=0

while [ $counter -lt 10 ]
do

    if [ $counter -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    counter=$((counter+1))
done
