#!/usr/bin/env bash
# Bash script that edits the hosts file to modify the localhost to resolve to 127.0.0.2
# and facebook.com to resolve to 8.8.8.8

# Because the checker is running on Docker, we need to make a copy of /etc/hosts,
# do our changes on the copy and then force copying it back to the original file.
# As Docker treats /etc/hosts differently. It overwrites it whenever it wants without any regard for your modifications.

cp /etc/hosts ~/new_hosts
sed -i 's/127.0.0.1/127.0.0.2/' ~/new_hosts
sed -i '2i8.8.8.8 facebook.com' ~/new_hosts
cp -f ~/new_hosts /etc/hosts

# sed: stream editor
# -i: edit in place
# 2i: insert in the second line
