#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine

# An Example of a network interface after running the ifconfig command:

# lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
#         inet 127.0.0.1  netmask 255.0.0.0
#         inet6 ::1  prefixlen 128  scopeid 0x10<host>
#         ...

# the inet field shows the IPv4 address assigned to the interface which we want to extract

ifconfig | grep "inet " | cut -d ' ' -f 10
