#!/usr/bin/env bash
# This script runs Nginx as the `nginx` user.
chmod +rwx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
ed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
